name: Release

on:
  pull_request:
    types: [closed]
    paths:
      - '.github/project.yml'

jobs:
  release:
    runs-on: ubuntu-latest
    name: release
    if: ${{github.event.pull_request.merged == true}}
    env:
      GITHUB_TOKEN: ${{secrets.RELEASE_TOKEN}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{secrets.RELEASE_TOKEN}}

      - name: Retrieve Project Metadata
        uses: radcortez/project-metadata-action@243817f1e0f2b4df4e012fc17efc45cff166425d
        id: metadata
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          metadata-file-path: '.github/project.yml'
          local-file: true

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@v1

      - name: Perform Maven Release
        run: |
          #git config --global user.name "github-actions[bot]"
          #git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "bf2-ci-bot"
          git checkout -b release
          mvn -B release:prepare -DreleaseVersion=${{steps.metadata.outputs.current-version}} -DdevelopmentVersion=${{steps.metadata.outputs.next-version}}
          git checkout ${{github.base_ref}}
          git rebase release
          export QUARKUS_CONTAINER_IMAGE_REGISTRY="${{secrets.IMAGE_REPO_HOSTNAME}}"
          export QUARKUS_CONTAINER_IMAGE_GROUP="${{secrets.IMAGE_REPO_NAMESPACE}}"
          export QUARKUS_CONTAINER_IMAGE_USERNAME="${{secrets.IMAGE_REPO_USERNAME}}"
          export QUARKUS_CONTAINER_IMAGE_PASSWORD="${{secrets.IMAGE_REPO_PASSWORD}}"
          # Build and push the release images using the commit tagged in `release:prepare`
          mvn -B -P docker release:perform

#       - name: Build and Push Image
#         run: |
#           # Use `target/checkout` as the Docker build PATH, Maven release:perform has generated the release artifacts in that location
#           docker login -u="${{secrets.IMAGE_REPO_USERNAME}}" -p="${{secrets.IMAGE_REPO_PASSWORD}}" ${{secrets.IMAGE_REPO_HOSTNAME}}
#           # docker build -t ${{secrets.IMAGE_REPO_HOSTNAME}}/${{secrets.IMAGE_REPO_NAMESPACE}}/kafka-admin-api:${{steps.metadata.outputs.current-version}} --build-arg kafka_admin_api_version=${{steps.metadata.outputs.current-version}} target/checkout/kafka-admin -f target/checkout/kafka-admin/src/main/docker/Dockerfile.jvm
#           mvn clean package -Pdocker -DskipTests -Dquarkus.container-image.image=${{secrets.IMAGE_REPO_HOSTNAME}}/${{secrets.IMAGE_REPO_NAMESPACE}}/kafka-admin-api:${{steps.metadata.outputs.current-version}}
#           docker push ${{secrets.IMAGE_REPO_HOSTNAME}}/${{secrets.IMAGE_REPO_NAMESPACE}}/kafka-admin-api:${{steps.metadata.outputs.current-version}}

      - name: Push Release Tag
        run: |
          git push
          git push --tags

      - name: Create GitHub Release
        uses: radcortez/milestone-release-action@98bd3321583e9bdbbe15c08fa4b2249371efaeaa
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          milestone-title: ${{steps.metadata.outputs.current-version}}
